### ISSUE TITLE
Task: Port Mesos Java Example to Mesomatic

### ISSUE THREAD

**Issue by oubiwann** [clojusc/mesomatic#10]
In creating a minimal "Hello World" Mesomatic example, I've found a couple of different bugs in Mesomatic ... but more than that, my own lack of confidence around the workings of Mesos and Mesomatic were exposed. So! Instead of continuing down that path, I'd like to port a know, working example to Mesosmatic:
- https://github.com/apache/mesos/blob/master/src/examples/java/TestFramework.java
- https://github.com/apache/mesos/blob/master/src/examples/java/TestExecutor.java

I'll be putting this code here:
- https://github.com/clojusc/mesomatic-examples

If, once created, it is something that would be beneficial to include in a `mesomatic/examples` dir, I'm all for that as well.

Once this is working (and any missing features are added to Mesomatic to support this), I will return to the super-minimal "Hello World" example and get that finished up.

Usage:
- Since `lein` is a near-ubiquitous tool in the Clojure community, it will be used to run the framework

Dependencies:
- This example will use a bare minimum of libraries in order to clearly illustrate a core usage pattern (mesomatic and mesos; maybe cli for parsing args passed to `main`)

Dev plan:
- [x] Create `test-framework.clj` as a port of `TestFramework.java`
- [x] Create `test-executor.clj` as a port of `TestExecutor.java`
- [x] Create `core.clj` with `main` function
- [x] Add `lein` alias(es) in `project.clj` for running framework and/or executor
- [x] Create tickets for all bug fixes/feature additions
- [x] Submit PRs for completed work on bug fix/new feature branches:
  - [x] DONE - https://github.com/clojusc/mesomatic/tree/add-opperation-type
  - [x] DONE - https://github.com/clojusc/mesomatic/tree/add-accept-offers - see issue #12; this has an open PR for it [here](https://github.com/pyr/mesomatic/pull/16)
  - [x] DONE - https://github.com/clojusc/mesomatic/tree/add-missing-methods - see issue #13; will rebase after PR #16 is merged
  - [x] DONE - https://github.com/clojusc/mesomatic/tree/add-missing-source - see issue #17; will rebase after PR #16 is merged
  - [x] DONE - https://github.com/clojusc/mesomatic/tree/cond-to-case (aesthetic only) - see issue #18; will rebase after PR #16 is merged
  - [x] DONE - https://github.com/clojusc/mesomatic/commits/fix-executor-registered - see issue #19; will rebase after previous three are merged
  - [x] DONE - https://github.com/clojusc/mesomatic/tree/add-implicit-acknowledgements - see issue #20; will rebase after previous branches are merged
- [x] Test all Mesomatic bug fixes/feature additions in a separate (cumulative) branch
- [x] Demonstrate the ability to send messages from the executor back to the scheduler
- [x] Ensure proper shutdown of framework upon successful completion of tasks
- [x] Perform a final compare & contrast between Java and Clojure versions to ensure implementation parity

**Comment by oubiwann** [comment]
Usage:
 * Since ``lein`` is a near-ubiquitous tool in the Clojure community, it will be used to run the framework

Dependencies:
 * This example will use a bare minimum of libraries in order to clearly illustrate a core usage pattern (mesomatic and mesos; maybe cli for parsing args passed to ``main``)

Dev plan:
 * Create ``test-framework.clj`` as a port of ``TestFramework.java``
 * Create ``test-executor.clj`` as a port of ``TestExecutor.java``
 * Create ``core.clj`` with ``main`` function
 * Add ``lein`` alias(es) in ``project.clj`` for running framework and/or executor

**Comment by oubiwann** [comment]
Making slow-but-steady progress on this. Probably past the half-way point now. Next steps:
- Schedule tasks
- Confirm execution
- Enable conditional short-circuiting (resource decrements, like in the Java example)

**Comment by oubiwann** [comment]
Got task scheduling running yesterday, but execution is err'ing (even though the command run by the executor succeeds with exit code `0`). I will be looking into this in the next day or so; until then, I won't be able to confirm example execution.

Also: got conditional short-circuiting finished last night.

**Comment by oubiwann** [comment]
One of the things the Java example has that Mesomatic doesn't support yet is the `accept-offers` method. The Mesos Java example has a code comment that the tasks feature will be deprecated at some point and that `accept-offers` is what should be used.

As such, two new tickets have been created for Mesomatic to address this:
- [x] [Feature: Add new Operation type](https://github.com/pyr/mesomatic/issues/11)
- [x] [Feature: Add new "accept-offers" method](https://github.com/pyr/mesomatic/issues/12)

**Comment by oubiwann** [comment]
Good news: it looks like the branches that implement the operation type and the `accept-offers` method work.

Bad news is that the same error with exit code `0` being a failure  is present. To be fair, I didn't expect that to magically go away with this change (can't deny the wishful thinking, though...!)

**Comment by oubiwann** [comment]
Making progress on the exit code thing (a red herring); should have this wrapped up in a few days (fingers crossed).

Also added the (much simpler) "exception" framework.

**Comment by oubiwann** [comment]
Got full end-to-end example working! There are some more PRs that I will submit that need to be in place in order for the example to work. Once those have been submitted and merged, it will probably be time to close this ticket :-)

I've updated the dev plan (see the ticket description) with the remaining tasks.

**Comment by oubiwann** [comment]
Okay, I've got the example ported (finally!) Of the 23 tasks identified on the main ticket (https://github.com/clojusc/mesomatic-examples/issues/3), 20 are done. The others are clean-up and logic tweaks. Right now, the logic is creating 5 tasks in 5 different executors. I'll update that to match the logical grouping done in the Java example (4 tasks in one executor, 1 task in another ... based upon using 4 CPUs per task).

Note, however, that there are several branches where Mesomatic needed to be updated in order for this to work. I'm only doing one PR at a time, so that I can rebase afterwards and ensure that subsequent PRs are clean.

I've updated the ticket description with the complete list of outstanding tickets/branches (roughly in the order which they should be merged).

Note that I've been testing/running with this branch (which has all the branches merged):
- https://github.com/clojusc/mesomatic/tree/deploy

Right now, using that `deploy` branch is the only way to run the Mesomatic/Clojure port of the Java Examples, since upstream (py/mesomatic) doesn't have all the missing features/fixes yet. As such, I'll keep this ticket open until upstream can support the examples.

**Comment by pyr** [comment]
@oubiwann does the last release fix your remaining blockers?

**Comment by oubiwann** [comment]
Yes! I need to update the examples to point to the release now ...

Thanks so much!

**Comment by oubiwann** [comment]
There is a bit more that would be good to do in the Mesomatic version of the Java example ... but I'll leave that as an exercise for the motivated contributor :-)

For interested parties, see the tickets here:
- https://github.com/clojusc/mesomatic-examples/issues

Closing!
